#!/bin/sh
if ! uci -q get argon.@global[0] >/dev/null 2>&1; then
    [ -f /etc/config/argon ] || touch /etc/config/argon
    uci add argon global
fi

uci set argon.@global[0].primary='#28a745'
uci set argon.@global[0].dark_primary='#4A6B5D'
uci set argon.@global[0].transparency='0.3'
uci commit argon
