#!/bin/sh /etc/rc.common
######################################################################
# vim: set ft=sh
# fix_luci_rpcd - 初始化 rpcd 空密码哈希
#
# 背景:
#   rpcd 密码必须是 crypt hash 格式（uci 不持久化空字符串），
#   首次开机/iStore 备份还原后需设置初始空密码哈希，
#   否则 LuCI 空密码登录返回 403。
#
# uhttpd 已作为原生包安装（CONFIG_PACKAGE_uhttpd=y），
# 不再需要适配器脚本。
#
# 时序:
#   START=11，在 fix_luci_ucode (START=10) 之后。
######################################################################

START=11

PROG=fix_luci_rpcd

# 空密码的 MD5-crypt hash（salt=luci，与 LuCI 默认一致）
EMPTY_HASH='$1$luci$kwi0krvQO9W2piJom/hF0.'

boot() {
    # 仅当 login section 存在但无 password 字段时设置空密码哈希
    # 不覆盖用户已在 LuCI 设置的密码
    if uci -q get rpcd.@login[0] >/dev/null 2>&1; then
        local current_pwd
        current_pwd=$(uci -q get rpcd.@login[0].password)
        if [ -z "$current_pwd" ]; then
            uci set rpcd.@login[0].password="$EMPTY_HASH"
            uci commit rpcd
            logger -t "$PROG" "initialized rpcd empty password hash"
        fi
    fi
}
